name: 'dbt_novadrive'
version: '1.0.0'

profile: 'dbt_novadrive'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


seeds:
  dbt_novadrive:
    +schema: raw_novadrive

models:
  dbt_novadrive:

    staging:
      +schema: stg_novadriva  # O dbt usará como base 'stg_novadriva'
      +materialized: view

    intermediate:
          +schema: int_novadriva
          +materialized: view

    marts:
          +schema: mart_novadriva
          +materialized: table